set nocompatible
filetype off

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'scrooloose/syntastic'
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'
Plugin 'hdima/python-syntax'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'bling/vim-airline'
Plugin 'mitsuhiko/vim-jinja'
Plugin 'Valloric/YouCompleteMe' 

call vundle#end()
filetype plugin indent on


" Settings
set colorcolumn=70,80
set encoding=utf-8
set nu
set pastetoggle=<F12> "http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste
set noswapfile
set nobackup
set clipboard=unnamedplus
set undolevels=1000

" Key-bindings
map <C-c><C-c> :w<CR>


" NERDTree
autocmd vimenter * NERDTree
let NERDTreeIgnore=['\.pyc$', '\~$', '__pycache__$[[dir]]', '\.egg-info$[[dir]]']


" Syntax Highlighting
colors seahorse
let python_highlight_all=1
syntax on


" Python
au BufNewFile,BufRead *.py silent 
    set filetype=python
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
    set autoindent
    set fileformat=unix


au BufNewFile,BufRead *.jinja2 silent
    set filetype=jinja
