set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" insert or delete brackets, parens, quotes in pair
Plugin 'jiangmiao/auto-pairs'
" a Git wrapper so awesome, it should be illegal
Plugin 'tpope/vim-fugitive'
" A Sublime-like minimap
Plugin 'severin-lemaignan/vim-minimap'
" file-system explorer
Plugin 'scrooloose/nerdtree'
" PEP 8 Indents
Plugin 'vim-scripts/indentpython.vim'
" Syntax checking hacks
Plugin 'scrooloose/syntastic'
Plugin 'jnurmine/Zenburn'
Plugin 'altercation/vim-colors-solarized'
Plugin 'hdima/python-syntax'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ

" Put your non-Plugin stuff after this line

" Key-bindings
map <C-c><C-c> :w<CR>

" Autorun
" autocmd vimenter * NERDTree

" Settings
set colorcolumn=80,70
set encoding=utf-8
set nu
let NERDTreeIgnore=['\.pyc$', '\~$']

" Syntax Highlighting
colors seahorse
let python_highlight_all=1
syntax on

" Python
au BufNewFile,BufRead *.py 
    set filetype=python
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
    set autoindent
    set fileformat=unix

" Whitespace is bad
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
