#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

bind '"[11~": "urxvt &\n"'

activate_venv() {
    source ~/.venvs/$1/bin/activate
}
new_venv() {
    python -m venv ~/.venvs/$1
}
alias venv=activate_venv
alias venvN=new_venv

